xtclang/xvm

- lib_web/src/main/x/web/MediaType.x
This is needed so web apps (UIs) can serve their own fonts (for example containing icons)
> Support for WOFF and WOFF2 media types (fonts)

- manualTests/build.gradle.kts
- manualTests/src/main/x/EchoTest.x
Create a new test (in the manual tests sub-project) that can be used by the Gradle build in lieu of the FizzBuzz test.
> Make an echo test specifically for gradle build use

- build-logic/common-plugins/src/main/kotlin/XdkDistribution.kt
Same as [this](https://github.com/xtclang/xvm/pull/152). Build should have no extraneous messages under normal successful execution. In the future, use --info to see these messages.
> Change the log level to "info" for expected "installDist" warning

- javatools/src/main/java/org/xvm/compiler/Compiler.java
- javatools/src/main/java/org/xvm/compiler/ast/NameExpression.java
- javatools/src/main/resources/errors.properties
- manualTests/src/main/x/TestSimple.x
A fix for issue https://github.com/xtclang/xvm/issues/155.
It's relatively simple. The only question in my mind: should it be a warning or an error?
> Add a compiler check for self-assigned properties

- build-logic/aggregator/src/main/kotlin/org.xtclang.build.aggregator.gradle.kts
- build-logic/common-plugins/src/main/kotlin/GitHubPackages.kt
- build-logic/common-plugins/src/main/kotlin/XdkDistribution.kt
- build.gradle.kts
- javatools/build.gradle.kts
- lib_ecstasy/build.gradle.kts
- plugin/build.gradle.kts
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcCompileTask.java
- xdk.properties
- xdk/build.gradle.kts
- xdk/settings.gradle.kts
- xdk/src/main/resources/xdk/bin/cfg_linux.sh
Added parameterizable distribution contents so we can modify it for several different Gradle distributions with different classifiers to get a more versatile release pipeline. Haven't actually done any yet, would want to discuss with @cpurdy first.
However, this should be possible to get in as a trivial abstraction raising change.
Also cleaned up several things related to the build, like dead code, unused configurations and so on.
> Add better abstraction to distribution building code.

- manualTests/build.gradle.kts
- plugin/src/main/java/org/xtclang/plugin/XtcLauncherTaskExtension.java
- plugin/src/main/java/org/xtclang/plugin/internal/DefaultXtcLauncherTaskExtension.java
- plugin/src/main/java/org/xtclang/plugin/launchers/JavaExecLauncher.java
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcCompileTask.java
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcLauncherTask.java
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcRunTask.java
You can configure debug, debugPort and debugSuspend (boolean, default to false, int default to 4711, and boolean default to true) in any launcher extension DSL, and override it in any launcher task.
> Added feedback from yesterday's meeting, with all debug properties now being both ENV vars and first class DSL members.

- javatools_launcher/build.gradle.kts
- manualTests/build.gradle.kts
- plugin/src/main/java/org/xtclang/plugin/ProjectDelegate.java
- plugin/src/main/java/org/xtclang/plugin/XtcBuildRuntimeException.java
- plugin/src/main/java/org/xtclang/plugin/XtcCompilerExtension.java
- plugin/src/main/java/org/xtclang/plugin/XtcPluginConstants.java
- plugin/src/main/java/org/xtclang/plugin/XtcProjectDelegate.java
- plugin/src/main/java/org/xtclang/plugin/internal/DefaultXtcCompilerExtension.java
- plugin/src/main/java/org/xtclang/plugin/internal/DefaultXtcLauncherTaskExtension.java
- plugin/src/main/java/org/xtclang/plugin/launchers/JavaExecLauncher.java
- plugin/src/main/java/org/xtclang/plugin/launchers/XtcLauncher.java
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcCompileTask.java
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcDefaultTask.java
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcLauncherTask.java
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcRunTask.java
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcSourceTask.java
- plugin/src/test/java/org/xtclang/plugin/SimpleXtcPluginTest.java
Changed the xtcCompile/compileXtc task default for the 'rebuild' flag to true. Stopped touching code as part of the rebuild config, because it is semantically incorrect. Cleaned up warnings. Added the property xtcDefaultRebuild, whose default is true, which will always add the --rebuild flag to the xcc process launched from the XtcCompileTask, as we know it is stale. This forces XTC to recompile XTC if any change has been made in Javatools, to ensure build soundness. To disable this, the property should be set to false, which will call xcc without --rebuild, potentially creating errors later, if the Javatools behavior changes.
Please test this with the xtcDefaultRebuild flag set to true and false and ensure it does what I think it does. Note that Gradle is smart enough to treat a very …
> Change the xtcCompile/compileXtc task default for the 'rebuild' flag and add an override

- javatools/src/main/java/org/xvm/runtime/template/_native/xTerminalConsole.java
- javatools_bridge/src/main/x/_native/TerminalConsole.x
- lib_cli/src/main/x/cli.x
- lib_ecstasy/src/main/x/ecstasy/io/Console.x
- manualTests/src/main/x/runner.x
- manualTests/src/main/x/webTests/Curl.x
- manualTests/src/main/x/webTests/Hello.x
The gist of the change is to add the "prompt" argument to the "readLine" API:
String readLine(String prompt = "", Boolean suppressEcho = False)
First, IMHO it's not a bad consolidation of steps that basically **always** come together - printing a prompt, suppressing a new line, immediately followed by the readLine() call.
However, I would not consider changing it right now if I didn't step on the following anomaly.
While trying to integrate [jline](https://github.com/jline/jline3) support into the native [TerminalConsole](https://github.com/xtclang/xvm/blob/master/javatools_bridge/src/main/x/_native/TerminalConsole.x) I observed a very weird behavior. When I used [the readLine API that takes a prompt as an argument](https://github.com/jline/jline3/blob/19c031c0bccaeea6a4346bc82c04c7bd3ec18 …
> Change the Console.readLine() API

- javatools/src/main/java/org/xvm/asm/constants/TypeConstant.java
- lib_ecstasy/src/main/x/ecstasy/collections/Map.x
- manualTests/src/main/x/TestSimple.x
About six month ago [we expanded Collection.toString() API](https://github.com/xtclang/xvm/commit/bd3e027dccf09e5a9716102eee49072f0fd67a14) to simplify the use of all the extra arguments on [appendTo() method](https://github.com/xtclang/xvm/blob/bd3e027dccf09e5a9716102eee49072f0fd67a14/lib_ecstasy/src/main/x/ecstasy/collections/Collection.x#L1108).
It seems very natural to do the same for the Map.toString().
As a minor wrinkle, while doing that change, I discovered two issues:
1.  An assertion in `TypeConstant.layerOnMethods()` that should've been an error.
2. An incorrect order of "re-base", "extends" and "into" contributions. Since the actual processing happens in reverse order (the last added contribution is processed first), the addition order should be "into", "extends" and "re-base" …
> Add default args for Map.toString() API

- javatools/src/main/java/org/xvm/runtime/template/numbers/BaseInt128.java
- lib_ecstasy/src/main/x/ecstasy/temporal/Duration.x
Modified Duration, supporting Durations less than 0 (e.g. already expired, in the past). Fixed a related bug this exposed in Int128.abs().
(This is for Gene's current project.)
> Modify Duration to support negative durations

- javatools/src/main/java/org/xvm/compiler/Parser.java
- manualTests/src/main/x/numbers.x
We were not correctly detecting EOF while parsing template expressions. Explicit EOF checking was based only on Lexer exhaustion, but that didn't account for the "current" token or the "push back" token. To complicate matters, when using the matching/peeking parsing helper methods, the parser will add a fake token (a closing curly brace) when EOF is encountered, so that deeply nested parsing code doesn't have to have to handle the repercussions of EOF until it comes back out from its deep recursion. Once we corrected the explicit EOF check to account for the current and push-back tokens, the pseudo token then obscured the EOF state, so we had to account for that as well. As a side-effect of fixing this, we uncovered an ancient syntax error (cut & pasted a half dozen times) in one of our …
> Resolve #191

- lib_ecstasy/src/main/x/ecstasy/collections/List.x
- manualTests/src/main/x/TestSimple.x
While working on something, I wrote a simple test similar to this:
Int[] ints = [3, 1, 2];
ints.sorted(inPlace=True);
console.print(ints);
and was quite surprised to see a non-sorted result. In a minute, I realized that our List.sorted() API contract takes the value of `inPlace` argument as a suggestion and not a requirement. If the List (in this case an Array) is immutable it creates a new array, sorts and returns it. I think it's wrong and it should throw.
Proposed is the corresponding API doc and implementation change
> Harden the List.sorted() contract

- javatools/src/main/java/org/xvm/runtime/Runtime.java
- javatools/src/main/java/org/xvm/runtime/template/_native/crypto/xRTAlgorithms.java
- javatools/src/main/java/org/xvm/runtime/template/_native/crypto/xRTCertificateManager.java
- javatools/src/main/java/org/xvm/runtime/template/_native/crypto/xRTDecryptor.java
- javatools/src/main/java/org/xvm/runtime/template/_native/crypto/xRTKeyStore.java
- javatools/src/main/java/org/xvm/runtime/template/_native/crypto/xRTSigner.java
- javatools/src/main/java/org/xvm/runtime/template/_native/web/xRTServer.java
- javatools/src/main/java/org/xvm/runtime/template/_native/xTerminalConsole.java
While working on the platform (host.xqiz.it) I realized that when the platform code calls some library methods that fail and then decides to pass the underlying exception message to the client (CLI or browser), that original exception message may contain some information that we should not reveal to the outside world. As a solution, I added `Runtime.logRuntimeException()` function that takes a potentially confidential text and turns it into a tag message. The original message gets logged to the system console, while the tag gets thrown.
> Add Runtime.logRuntimeException() API

- .github/workflows/xvm-verify-push.yml
This way, we may be able to better reproduce any issues that may crop up in the manualTests, due to assumptions about path assignments, for example with System.getPropert("java.io.tmpdir")
> Dump Java system properties in Github workflow

- javatools/src/main/java/org/xvm/runtime/template/xEnum.java
Markus noticed an exception [in the log](https://scans.gradle.com/s/yysm4q3h6swfs/console-log/raw) for "runParallel" on GitHib:
java.lang.ClassCastException: class org.xvm.runtime.ObjectHandle$InitializingHandle cannot be cast to class org.xvm.runtime.template.xEnum$EnumHandle (org.xvm.runtime.ObjectHandle$InitializingHandle and org.xvm.runtime.template.xEnum$EnumHandle are in unnamed module of loader 'app')
at org.xvm.runtime.template.xEnum.createConstHandle(xEnum.java:102)
at org.xvm.runtime.Utils.constructSingletonHandle(Utils.java:710)
at org.xvm.runtime.Utils$1.process(Utils.java:630)
at org.xvm.runtime.ServiceContext.execute(ServiceContext.java:638)
at org.xvm.runtime.ServiceContext.drainWork(ServiceContext.java:361)
at org.xvm.runtime.ServiceContext.execute(ServiceContext.java:412) …
> Remove an unnecessary cast

- javatools/src/main/java/org/xvm/compiler/ast/DelegatingExpression.java
- javatools/src/main/java/org/xvm/compiler/ast/Expression.java
- javatools/src/main/java/org/xvm/compiler/ast/ReturnStatement.java
- javatools/src/main/java/org/xvm/compiler/ast/TernaryExpression.java
- manualTests/src/main/x/TestSimple.x
Cliff reported a compiler bug: failure to compile a nested ternary:
conditional String test(Boolean b0, Boolean b1) {
return b0
? (b1 ? False : (True,"def"))
: (b1 ? (True,"abc") : (True, "xyz"));
}
This change fixes it as well as simplifies the BAST production of ReturnStatement
> Fix a compiler bug

- .github/workflows/cleaners.yml
- .github/workflows/xvm-verify-push.yml
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcDefaultTask.java
- plugin/src/main/java/org/xtclang/plugin/tasks/XtcLauncherTask.java
Added various simplifications and more robust GitHub actions for the check-in test. Also added stale data cleaners, but disabled.
This needs to be merged to master for the workflow_dispatch manual activation selector to get activated. None of the cleanup jobs for old maven packages, caches or workflow results are enabled in the first merge. Nor are they run on a repeated schedule with cron. This is to make sure that they work as they should, and we will tune these and debug them in the next pull request after these are merged. 
There, I will add release publication + jreleaser support for release packaging.
> Add various simplifications and more robust GitHub actions for the check-in test

- lib_web/src/main/x/web/WebService.x
- lib_xenia/src/main/x/xenia.x
- lib_xenia/src/main/x/xenia/Catalog.x
- lib_xenia/src/main/x/xenia/ChainBundle.x
- lib_xenia/src/main/x/xenia/HttpHandler.x
- lib_xenia/src/main/x/xenia/SystemService.x
- manualTests/src/main/x/webTests/Hello.x
HttpHandler was designed for "declarative" endpoint discovery, driven by the reflection on WebServices and their methods declarations. As a result of that design all WebServices had to have default constructors and be a part of the compilation unit of the corresponding WebApp. This change removes those limitations by a allowing to:
a) declare WebServices with non-default constructors 
b) use WebServices that are external to the underlying WebApp
> Allow adding extra WebServices to the HttpHandler

- javatools/src/main/java/org/xvm/runtime/template/_native/crypto/xRTCertificateManager.java
- javatools_bridge/src/main/x/_native/crypto/RTCertificateManager.x
- lib_crypto/src/main/x/crypto/CertificateManager.x
- manualTests/src/main/x/crypto.x
All the KeyStore API was intentionally design in such a way that if if you ask for a private key [of a key pair] or a symmetrical [secret] key, you would get an object that **could** be used as such a secret, but a developer would have no way to extract/expose the actual key material. Now, for the reverse proxy management project, we came to a requirement to get access/propagate that vulnerable data outside of the single machine boundaries.
The KeyStore [injectable] interface is meant to be read only, and all the keystore mutations are contained in the CertificateManager [injectable] interface. This change adds an API to the latter that allows the developer (at this time most likely just us as developers of the platform) to extract the raw key material from the keystore.
> Add CertificateManager.extractKey() API

- javatools/src/main/java/org/xvm/asm/constants/IntersectionTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/ParameterizedTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/RelationalTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/TerminalTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/TypeConstant.java
- javatools/src/main/java/org/xvm/compiler/ast/NameExpression.java
- javatools/src/main/java/org/xvm/compiler/ast/TupleExpression.java
- javatools/src/main/java/org/xvm/runtime/template/collections/xTuple.java
- lib_json/src/main/x/json/mappings/TupleMapping.x
- manualTests/src/main/x/IO.x
- manualTests/src/main/x/TestSimple.x
Fix serialization of tuples containing enum values, such as:
Tuple<Int, Boolean> tuple = (1, True)
Prior to this change json serialization would blow up at run time.
> Fix Json serialization for Tuples of enum values

- javatools/src/main/java/org/xvm/asm/constants/DynamicFormalConstant.java
- javatools/src/main/java/org/xvm/asm/constants/TypeConstant.java
- javatools/src/main/java/org/xvm/asm/op/JumpIsA.java
- javatools/src/main/java/org/xvm/runtime/ClassTemplate.java
- javatools/src/main/java/org/xvm/runtime/ObjectHandle.java
- javatools/src/main/java/org/xvm/runtime/ProxyComposition.java
- javatools/src/main/java/org/xvm/runtime/Runtime.java
- javatools/src/main/java/org/xvm/runtime/ServiceContext.java
- javatools/src/main/java/org/xvm/runtime/template/Proxy.java
- javatools/src/main/java/org/xvm/runtime/template/_native/reflect/xRTFunction.java
- javatools/src/main/java/org/xvm/runtime/template/_native/reflect/xRTMethod.java
- javatools/src/main/java/org/xvm/runtime/template/_native/reflect/xRTType.java
- javatools/src/main/java/org/xvm/runtime/template/collections/xTuple.java
- javatools/src/main/java/org/xvm/runtime/template/reflect/xClass.java
- manualTests/src/main/x/reflect.x
There was a number of "TODO"s at xRTType.java to implement reflection API against "foreign" types (object of type Type, that belong to another container's type system)
This PR implements them.
> Fix native reflection support for foreign types

- javatools/src/main/java/org/xvm/asm/ConstantPool.java
- javatools/src/main/java/org/xvm/runtime/NestedContainer.java
- javatools/src/main/java/org/xvm/runtime/template/_native/mgmt/xContainerControl.java
- javatools/src/main/java/org/xvm/runtime/template/_native/mgmt/xContainerLinker.java
- lib_ecstasy/src/main/x/ecstasy.x
- lib_ecstasy/src/main/x/ecstasy/Closeable.x
- lib_ecstasy/src/main/x/ecstasy/mgmt/ResourceProvider.x
Currently, the API for ResourceProvider which is used to control injections into a newly created Container doesn't have any lifecycle events. It becomes a problem when a custom ResourceProvider injects a lifecycle aware (Closeable) resource into a child container. When that container is "killed", the resources may leak, since no one properly "closes" them.
This change addresses the issue my making the ResourceProvider to extend Closeable and guaranteeing a RT call to close() when the container goes away.
Cameron suggested a bit more elaborate extension to the ResourceProvider API:
```
/**
* At the point that the container (for which this ResourceProvider exists) is shut down or
* killed, this method will be invoked and passed a list of all resources previously supplied
* that implements …
```
> Add lifecycle support to ResourceProvider

- doc/todo-list.txt
- javatools/src/main/java/org/xvm/runtime/Container.java
- javatools/src/main/java/org/xvm/runtime/DebugConsole.java
- javatools/src/main/java/org/xvm/runtime/Fiber.java
- javatools/src/main/java/org/xvm/runtime/ServiceContext.java
- javatools/src/main/java/org/xvm/runtime/Utils.java
- javatools/src/main/java/org/xvm/runtime/template/_native/temporal/xLocalClock.java
- javatools/src/main/java/org/xvm/runtime/template/_native/temporal/xNanosTimer.java
- javatools/src/main/java/org/xvm/runtime/template/_native/web/xRTConnector.java
- javatools/src/main/java/org/xvm/runtime/template/xException.java
- javatools/src/main/java/org/xvm/runtime/template/xService.java
- manualTests/src/main/x/TestSimple.x
When you used the Console Debugger for stepping through Ecstasy code, it used to be extremely hard to investigate any timer related logic, since stopping in the debugger didn't prevent the alarms to go off based on the wall clock.
This change allows the debugger to "freeze" time for all containers, dramatically simplifying such a debugging.
> Introduce native Container API to freeze time; make the console debugger to freeze all containers

- javatools/src/main/java/org/xvm/asm/Register.java
- javatools/src/main/java/org/xvm/asm/ast/ConvertExprAST.java
- javatools/src/main/java/org/xvm/asm/ast/StmtExprAST.java
- javatools/src/main/java/org/xvm/compiler/ast/AssignmentStatement.java
- javatools/src/main/java/org/xvm/compiler/ast/ConvertExpression.java
- javatools/src/main/java/org/xvm/compiler/ast/InvocationExpression.java
- manualTests/src/main/x/TestSimple.x
Consider a function:
(Int32, Int32) f() {...}
that is being used like this:
(Int x, Int y) = f();
For such a call, we used to produce a BAST tree that combined a ConvertAST with a multi-return CallAST, which was hard to process by the back-end compiler. This change simplifies the BAST production by splitting the call and conversion, basically turning the code above into this:
(Int32 tmpX, Int32 tmpY) = f();
Int x = tmpX.toInt64();
Int y = tmpY.toInt64();
> Simplify multi-value conversion AST production

- Makefile
- javatools_backend/src/main/java/org/xvm/xtc/FilePart.java
- tck/src/main/x/tck.x
Bump version #, add lib_convert, turn off newly broken TCKs
> Fix tcks on TOT master

- manualTests/src/main/x/json/json_test/JsonArrayTest.x
- manualTests/src/main/x/json/json_test/JsonBuilderTest.x
- manualTests/src/main/x/json/json_test/patch/JsonPatchAddTest.x
- manualTests/src/main/x/json/json_test/patch/JsonPatchCopyTest.x
- manualTests/src/main/x/json/json_test/patch/JsonPatchMoveTest.x
- manualTests/src/main/x/json/json_test/patch/JsonPatchOperationTest.x
- manualTests/src/main/x/json/json_test/patch/JsonPatchRemoveTest.x
- manualTests/src/main/x/json/json_test/patch/JsonPatchReplaceTest.x
- manualTests/src/main/x/json/json_test/patch/JsonPatchTestTest.x
I think it's makes the tests look better if we don't have to explicitly specify types for homogenous JsonObject constants
> Remove unnecessary type declarations

- gradle/libs.versions.toml
- javatools/src/main/java/org/xvm/asm/constants/RecursiveTypeConstant.java
- javatools/src/main/java/org/xvm/asm/op/Var_S.java
- javatools/src/main/java/org/xvm/asm/op/Var_SN.java
- javatools/src/main/java/org/xvm/compiler/ast/AnnotatedTypeExpression.java
- javatools/src/main/java/org/xvm/compiler/ast/ListExpression.java
- lib_cli/src/main/x/cli.x
- lib_cli/src/main/x/cli/Runner.x
- lib_cli/src/main/x/cli/Scanner.x
- lib_web/src/main/x/web/Client.x
- lib_webcli/build.gradle.kts
- lib_webcli/src/main/x/webcli.x
- manualTests/src/main/x/cliTest.x
- manualTests/src/main/x/webTests/HelloClient.x
- xdk/build.gradle.kts
- xdk/settings.gradle.kts
Add a facility to easily create REST based CLI application
> Introduce webcli module

- lib_json/src/main/x/json/JsonArrayBuilder.x
- lib_json/src/main/x/json/JsonBuilder.x
- lib_json/src/main/x/json/JsonMergePatch.x
- lib_json/src/main/x/json/JsonObjectBuilder.x
- lib_json/src/main/x/json/JsonPatch.x
- lib_json/src/main/x/json/JsonPointer.x
- lib_net/src/main/x/net/Uri.x
- manualTests/src/main/x/json/json_test/JsonBuilderTest.x
- manualTests/src/main/x/json/json_test/JsonMergePatchTest.x
While using JsonPointer API I noticed that some of the docs are formatted with a style different from other classes in this package. This is a trivial change - put there as a draft for JK to review two suspicious places in the code
> Reformat docs; minor fixes

- javatools/src/main/java/org/xvm/asm/constants/AbstractDependantChildTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/DifferenceTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/IntersectionTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/ParameterizedTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/PropertyClassTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/RecursiveTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/RelationalTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/TerminalTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/TypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/TypeSequenceTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/UnionTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/UnresolvedTypeConstant.java
- javatools/src/main/java/org/xvm/runtime/ClassTemplate.java
- javatools/src/main/java/org/xvm/runtime/template/xException.java
- lib_ecstasy/src/main/x/ecstasy/io/TextPosition.x
- lib_json/src/main/x/json/Lexer.x
- manualTests/src/main/x/TestSimple.x
It's possible for a class or interface to be declared as immutable, for example:
interface TextPosition
extends immutable Hashable {
}
If a class implements such an interface, the runtime must enforce a newly constructed object immutability before it becomes "visible".
> Enforce immutability of an immutable not const type

- lib_net/src/main/x/net/IPAddress.x
The code masked only a nibble instead of a byte which caused incorrect results.
> Fix an incorrect and-mask

- javatools/src/main/java/org/xvm/asm/Component.java
- javatools/src/main/java/org/xvm/asm/constants/DifferenceTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/ImmutableTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/IntersectionTypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/TypeConstant.java
- javatools/src/main/java/org/xvm/asm/constants/TypeSequenceTypeConstant.java
- javatools/src/main/java/org/xvm/compiler/ast/DecoratedTypeExpression.java
- javatools/src/main/java/org/xvm/compiler/ast/ListExpression.java
- javatools/src/main/java/org/xvm/compiler/ast/NameExpression.java
- javatools/src/main/java/org/xvm/compiler/ast/NamedTypeExpression.java
- javatools/src/main/java/org/xvm/compiler/ast/TupleExpression.java
- javatools/src/main/java/org/xvm/runtime/ClassTemplate.java
- javatools/src/main/java/org/xvm/runtime/template/_native/reflect/xRTType.java
- javatools/src/main/java/org/xvm/runtime/template/xConst.java
- manualTests/src/main/x/TestSimple.x
A number of DBObject derived types require `immutable Const` parameters, for example:
`interface DBMap<Key extends immutable Const, Value extends immutable Const>`
However, the compiler would allow the following declaration:
`mixin MyTable into DBMap<String, Int[]>`
instead of the correct one:
`mixin MyTable into DBMap<String, immutable Int[]>`
This would result in a run-time exception.
This change fixes that compiler deficiency. An additional benefit is a compiler check for the actual value types for DBMap method calls, such as `put(key, value)`, forcing the value to be known an `immutable Const` at compile time
> Fix isA() implementation for immutable types
